name: sbt test

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install locales
      run: sudo apt-get -y install locales
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: temurin
    - name: Run Tests
      run: sbt "coverage; test; coverageReport; coverageAggregate;"
    - name: Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: target/scala-2.13/coverage-report/cobertura.xml
        badge: true
        format: 'markdown'
        indicators: false
        hide_complexity: true
        output: 'both'
    - name: Coverage Report Pull Request Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    - name: Coverage Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
