name: Build and Publish Docker Image

on:
  release:
    types: [released]

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: temurin
    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Publish Docker Image
      run: sbt docker:publish
      env:
        DOCKER_UPDATE_LATEST: true
